# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2017 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

version: '2.1'

services:
  test-service_base:
    # Overrides default inspirehep config.
    extends:
      file: services.yml
      service: base
    environment:
      - APP_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://inspirehep:dbpass123@test-database:5432/inspirehep
      - APP_BROKER_URL=amqp://guest:guest@test-rabbitmq:5672//
      - APP_CELERY_RESULT_BACKEND=amqp://guest:guest@test-rabbitmq:5672//
      - APP_CACHE_REDIS_URL=redis://test-redis:6379/0
      - APP_ACCOUNTS_SESSION_REDIS_URL=redis://test-redis:6379/2
      - APP_SEARCH_ELASTIC_HOSTS=test-indexer

  unit:
    extends:
      service: test-service_base
    volumes_from:
      - test-static
    command: bash -c "py.test inspirehep tests/unit && make -C docs html"

  workflows:
    extends:
      service: test-service_base
    command: py.test tests/integration/workflows
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started

  integration:
    extends:
      service: test-service_base
    command: py.test tests/integration --ignore tests/integration/workflows
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started

  acceptance:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/acceptance
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  visible_acceptance:
    extends:
      service: test-service_base
    command: py.test --driver Firefox --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/acceptance
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000
      - DISPLAY=$DISPLAY

  acceptance-authors:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/acceptance/authors
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  acceptance-literature:
    extends:
      service: test-service_base
    command: py.test --driver Remote --host selenium --port 4444 --capability browserName firefox --html=selenium-report.html tests/acceptance/literature
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
      test-worker:
        condition: service_started
      selenium:
        condition: service_started
      test-web:
        condition: service_started
    environment:
      - SERVER_NAME=test-web:5000

  test-web:
    extends:
      service: test-service_base
    command: gunicorn -b 0.0.0.0:5000 -t 3600 -w 1 --access-logfile "-" inspirehep.wsgi_with_coverage:application
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy
    environment:
      - APP_SERVER_NAME=test-web:5000

  test-worker:
    extends:
      service: test-service_base
    command: celery worker -E -A inspirehep.celery --loglevel=INFO --purge
    volumes_from:
      - test-static
    depends_on:
      test-database:
        condition: service_healthy
      test-indexer:
        condition: service_healthy
      test-rabbitmq:
        condition: service_healthy
      test-redis:
        condition: service_healthy

  test-redis:
    image: redis:3.2.3
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "bash"
        - "-c"
        - "exec 3<> /dev/tcp/127.0.0.1/6379 && echo PING >&3 && head -1 <&3 | grep PONG"

  test-indexer:
    extends:
      file: services.yml
      service: indexer
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "curl http://localhost:9200/_cluster/health | grep '.status.:.\\(green\\|yellow\\)'"

  test-rabbitmq:
    image: rabbitmq
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD"
        - "rabbitmqctl"
        - "status"

  test-database:
    extends:
      file: services.yml
      service: database
    healthcheck:
      timeout: 5s
      interval: 5s
      retries: 5
      test:
        - "CMD-SHELL"
        - "pg_isready --dbname=inspirehep --host=localhost --username=inspirehep"

  selenium:
    image: selenium/standalone-firefox:2.53.1-beryllium

  test-static:
    extends:
      file: services.yml
      service: static
