# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 CERN.
#
# inspirehep is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

FROM elasticsearch:7.1.1

RUN bin/elasticsearch-plugin install -b analysis-icu
