# -*- coding: utf-8 -*-
#
# This file is part of INSPIRE.
# Copyright (C) 2016 CERN.
#
# INSPIRE is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307, USA.
#
# In applying this license, CERN does not
# waive the privileges and immunities granted to it by virtue of its status
# as an Intergovernmental Organization or submit itself to any jurisdiction.

import json
import os
import pkg_resources


COUNTRIES_TO_CONTINETS = {
    'AB': {'continent': ['Europe'], 'name': 'Serbia and Montenegro'},
    'AD': {'continent': ['Europe'], 'name': 'Andorra'},
    'AF': {'continent': ['Asia'], 'name': 'Afghanistan'},
    'AG': {'continent': ['North America'],
           'name': 'Antigua and Barbuda'},
    'AI': {'continent': ['North America'], 'name': 'Anguilla'},
    'AL': {'continent': ['Europe'], 'name': 'Albania'},
    'AQ': {'continent': ['Antarctica'], 'name': 'Antarctica'},
    'AM': {'continent': ['Asia'], 'name': 'Armenia'},
    'AN': {'continent': ['North America'], 'name': 'Netherlands Antilles'},
    'AO': {'continent': ['Africa'], 'name': 'Angola'},
    'AR': {'continent': ['South America'], 'name': 'Argentina'},
    'AS': {'continent': ['Oceania'], 'name': 'American Samoa'},
    'AT': {'continent': ['Europe'], 'name': 'Austria'},
    'AU': {'continent': ['Oceania'], 'name': 'Australia'},
    'AX': {'continent': ['Europe'], 'name': 'Aland Islands'},
    'AW': {'continent': ['North America'], 'name': 'Aruba'},
    'AZ': {'continent': ['Asia', 'Europe'], 'name': 'Azerbaijan'},
    'BB': {'continent': ['North America'], 'name': 'Barbados'},
    'BD': {'continent': ['Asia'], 'name': 'Bangladesh'},
    'BE': {'continent': ['Europe'], 'name': 'Belgium'},
    'BF': {'continent': ['Africa'], 'name': 'Burkina Faso'},
    'BG': {'continent': ['Europe'], 'name': 'Bulgaria'},
    'BH': {'continent': ['Asia'], 'name': 'Bahrain'},
    'BI': {'continent': ['Africa'], 'name': 'Burundi'},
    'BJ': {'continent': ['Africa'], 'name': 'Benin'},
    'BM': {'continent': ['North America'], 'name': 'Bermuda'},
    'BN': {'continent': ['Asia'], 'name': 'Brunei Darussalam'},
    'BO': {'continent': ['South America'], 'name': 'Bolivia'},
    'BR': {'continent': ['South America'], 'name': 'Brazil'},
    'BS': {'continent': ['North America'], 'name': 'Bahamas'},
    'BT': {'continent': ['Asia'], 'name': 'Bhutan'},
    'BQ': {'continent': ['North America'], 'name': 'Caribbean Netherlands'},
    'BV': {'continent': ['Antarctica'], 'name': 'Bouvet Island'},
    'BW': {'continent': ['Africa'], 'name': 'Botswana'},
    'BY': {'continent': ['Europe'], 'name': 'Belarus'},
    'BZ': {'continent': ['North America'], 'name': 'Belize'},
    'CA': {'continent': ['North America'], 'name': 'Canada'},
    'CC': {'continent': ['Asia'], 'name': 'Cocos Islands'},
    'CD': {'continent': ['Africa'],
           'name': 'Democratic Republic of the Congo'},
    'CG': {'continent': ['Africa'], 'name': 'Republic of the Congo'},
    'CI': {'continent': ['Africa'], 'name': "Cote d'Ivoire"},
    'CK': {'continent': ['Oceania'], 'name': 'Cook Islands'},
    'CL': {'continent': ['South America'], 'name': 'Chile'},
    'CM': {'continent': ['Africa'], 'name': 'Cameroon'},
    'CN': {'continent': ['Asia'],
           'name': "People's Republic of China"},
    'CO': {'continent': ['South America'], 'name': 'Colombia'},
    'CR': {'continent': ['North America'], 'name': 'Costa Rica'},
    'CS': {'continent': ['Europe'], 'name': 'Czechoslovakia'},
    'CU': {'continent': ['North America'], 'name': 'Cuba'},
    'CW': {'continent': ['North America', 'South America'], 'name': 'Curaçao'},
    'CV': {'continent': ['Africa'], 'name': 'Cape Verde'},
    'CX': {'continent': ['Asia'], 'name': 'Christmas Island'},
    'CY': {'continent': ['Asia'], 'name': 'Cyprus'},
    'CZ': {'continent': ['Europe'], 'name': 'Czech Republic'},
    'DE': {'continent': ['Europe'], 'name': 'Germany'},
    'DJ': {'continent': ['Africa'], 'name': 'Djibouti'},
    'DK': {'continent': ['Europe'], 'name': 'Denmark'},
    'DM': {'continent': ['North America'], 'name': 'Dominica'},
    'DO': {'continent': ['North America'],
           'name': 'Dominican Republic'},
    'EC': {'continent': ['South America'], 'name': 'Ecuador'},
    'EE': {'continent': ['Europe'], 'name': 'Estonia'},
    'EG': {'continent': ['Africa', 'Asia'], 'name': 'Egypt'},
    'ER': {'continent': ['Africa'], 'name': 'Eritrea'},
    'ET': {'continent': ['Africa'], 'name': 'Ethiopia'},
    'FI': {'continent': ['Europe'], 'name': 'Finland'},
    'FJ': {'continent': ['Oceania'], 'name': 'Fiji'},
    'FK': {'continent': ['South America'], 'name': 'Falkland Islands'},
    'FO': {'continent': ['Europe'], 'name': 'Faroe Islands'},
    'FR': {'continent': ['Europe'], 'name': 'France'},
    'GA': {'continent': ['Africa'], 'name': 'Gabon'},
    'GE': {'continent': ['Asia', 'Europe'], 'name': 'Georgia'},
    'GF': {'continent': ['South America'], 'name': 'French Guiana'},
    'GG': {'continent': ['Europe'], 'name': 'Guernsey'},
    'GH': {'continent': ['Africa'], 'name': 'Ghana'},
    'GI': {'continent': ['Africa', 'Europe'], 'name': 'Gibraltar'},
    'GL': {'continent': ['North America'], 'name': 'Greenland'},
    'GM': {'continent': ['Africa'], 'name': 'The Gambia'},
    'GN': {'continent': ['Africa'], 'name': 'Guinea'},
    'GP': {'continent': ['North America'], 'name': 'Guadeloupe'},
    'GR': {'continent': ['Europe'], 'name': 'Greece'},
    'GT': {'continent': ['North America'], 'name': 'Guatemala'},
    'GT': {'continent': ['North America'], 'name': 'Haiti'},
    'GU': {'continent': ['Oceania'], 'name': 'Guam'},
    'GW': {'continent': ['Africa'], 'name': 'Guinea-Bissau'},
    'GY': {'continent': ['South America'], 'name': 'Guyana'},
    'HK': {'continent': ['Asia'], 'name': 'Hong Kong'},
    'HM': {'continent': ['Oceania'],
           'name': 'Territory of Heard Island and McDonald Islands'},
    'HN': {'continent': ['North America'], 'name': 'Honduras'},
    'HT': {'continent': ['North America'], 'name': 'Haiti'},
    'HU': {'continent': ['Europe'], 'name': 'Hungary'},
    'ID': {'continent': ['Asia'], 'name': 'Indonesia'},
    'IE': {'continent': ['Europe'], 'name': 'Republic of Ireland'},
    'IL': {'continent': ['Asia'], 'name': 'Israel'},
    'IM': {'continent': ['Europe'], 'name': 'Isle of Man'},
    'IN': {'continent': ['Asia'], 'name': 'India'},
    'IO': {'continent': ['Asia'], 'name': 'British Indian Ocean Territorys'},
    'IQ': {'continent': ['Asia'], 'name': 'Iraq'},
    'IR': {'continent': ['Asia'], 'name': 'Iran'},
    'IS': {'continent': ['Europe'], 'name': 'Iceland'},
    'IT': {'continent': ['Europe'], 'name': 'Italy'},
    'JE': {'continent': ['Europe'], 'name': 'Jersey'},
    'JM': {'continent': ['North America'], 'name': 'Jamaica'},
    'JO': {'continent': ['Asia'], 'name': 'Jordan'},
    'JP': {'continent': ['Asia'], 'name': 'Japan'},
    'KE': {'continent': ['Africa'], 'name': 'Kenya'},
    'KG': {'continent': ['Asia'], 'name': 'Kyrgyzstan'},
    'KI': {'continent': ['Oceania'], 'name': 'Kiribati'},
    'KP': {'continent': ['Asia'], 'name': 'North Korea'},
    'KR': {'continent': ['Asia'], 'name': 'South Korea'},
    'KW': {'continent': ['Asia'], 'name': 'Kuwait'},
    'KY': {'continent': ['North America'], 'name': 'Cayman Islands'},
    'LB': {'continent': ['Asia'], 'name': 'Lebanon'},
    'LI': {'continent': ['Europe'], 'name': 'Liechtenstein'},
    'LR': {'continent': ['Africa'], 'name': 'Liberia'},
    'LS': {'continent': ['Africa'], 'name': 'Lesotho'},
    'LT': {'continent': ['Europe'], 'name': 'Lithuania'},
    'LU': {'continent': ['Europe'], 'name': 'Luxembourg'},
    'LV': {'continent': ['Europe'], 'name': 'Latvia'},
    'LY': {'continent': ['Africa'], 'name': 'Libya'},
    'MG': {'continent': ['Africa'], 'name': 'Madagascar'},
    'MH': {'continent': ['Oceania'], 'name': 'Marshall Islands'},
    'MK': {'continent': ['Europe'], 'name': 'Macedonia'},
    'ML': {'continent': ['Africa'], 'name': 'Mali'},
    'MM': {'continent': ['Asia'], 'name': 'Myanmar'},
    'MN': {'continent': ['Asia'], 'name': 'Mongolia'},
    'MO': {'continent': ['Asia'], 'name': 'Macao'},
    'MP': {'continent': ['Oceania'], 'name': 'Northern Mariana Islands'},
    'MQ': {'continent': ['North America'], 'name': ' Martinique'},
    'MR': {'continent': ['Africa'], 'name': 'Mauritania'},
    'MS': {'continent': ['North America'], 'name': 'Montserrat'},
    'MT': {'continent': ['Europe'], 'name': 'Malta'},
    'MU': {'continent': ['Africa'], 'name': 'Mauritius'},
    'MV': {'continent': ['Asia'], 'name': 'Maldives'},
    'MW': {'continent': ['Africa'], 'name': 'Malawi'},
    'MX': {'continent': ['North America'], 'name': 'Mexico'},
    'MY': {'continent': ['Asia'], 'name': 'Malaysia'},
    'MZ': {'continent': ['Africa'], 'name': 'Mozambique'},
    'NA': {'continent': ['Africa'], 'name': 'Namibia'},
    'NC': {'continent': ['Oceania'], 'name': 'New Caledonia'},
    'NE': {'continent': ['Africa'], 'name': 'Niger'},
    'NF': {'continent': ['Oceania'], 'name': 'Norfolk Island'},
    'NG': {'continent': ['Africa'], 'name': 'Nigeria'},
    'NI': {'continent': ['North America'], 'name': 'Nicaragua'},
    'NL': {'continent': ['Europe'],
           'name': 'Kingdom of the Netherlands'},
    'NO': {'continent': ['Europe'], 'name': 'Norway'},
    'NP': {'continent': ['Asia'], 'name': 'Nepal'},
    'NR': {'continent': ['Oceania'], 'name': 'Nauru'},
    'NT': {'continent': [], 'name': 'Neutral Zone'},
    'NU': {'continent': ['Oceania'], 'name': 'Niue'},
    'NZ': {'continent': ['Oceania'], 'name': 'New Zealand'},
    'OM': {'continent': ['Asia'], 'name': 'Oman'},
    'PA': {'continent': ['North America'], 'name': 'Panama'},
    'PE': {'continent': ['South America'], 'name': 'Peru'},
    'PF': {'continent': ['Oceania'], 'name': 'French Polynesia'},
    'PG': {'continent': ['Oceania'], 'name': 'Papua New Guinea'},
    'PH': {'continent': ['Asia'], 'name': 'Philippines'},
    'PK': {'continent': ['Asia'], 'name': 'Pakistan'},
    'PL': {'continent': ['Europe'], 'name': 'Poland'},
    'PN': {'continent': ['Oceania'], 'name': 'Pitcairn Islands'},
    'PS': {'continent': ['Asia'], 'name': 'Palestine'},
    'PT': {'continent': ['Europe'], 'name': 'Portugal'},
    'PW': {'continent': ['Oceania'], 'name': 'Palau'},
    'PY': {'continent': ['South America'], 'name': 'Paraguay'},
    'QA': {'continent': ['Asia'], 'name': 'Qatar'},
    'RO': {'continent': ['Europe'], 'name': 'Romania'},
    'RU': {'continent': ['Asia', 'Europe'], 'name': 'Russia'},
    'RW': {'continent': ['Africa'], 'name': 'Rwanda'},
    'SA': {'continent': ['Asia'], 'name': 'Saudi Arabia'},
    'SB': {'continent': ['Oceania'], 'name': 'Solomon Islands'},
    'SC': {'continent': ['Africa'], 'name': 'Seychelles'},
    'SD': {'continent': ['Africa'], 'name': 'Sudan'},
    'SE': {'continent': ['Europe'], 'name': 'Sweden'},
    'SG': {'continent': ['Asia'], 'name': 'Singapore'},
    'SI': {'continent': ['Europe'], 'name': 'Slovenia'},
    'SK': {'continent': ['Europe'], 'name': 'Slovakia'},
    'SL': {'continent': ['Africa'], 'name': 'Sierra Leone'},
    'SM': {'continent': ['Europe'], 'name': 'San Marino'},
    'SN': {'continent': ['Africa'], 'name': 'Senegal'},
    'SO': {'continent': ['Africa'], 'name': 'Somalia'},
    'SR': {'continent': ['South America'], 'name': 'Suriname'},
    'ST': {'continent': ['Africa'], 'name': 'Sao Tome and Principe'},
    'SY': {'continent': ['Asia'], 'name': 'Syria'},
    'TF': {'continent': ['Africa', 'Antarctica'],
           'name': 'French Southern Territories'},
    'TG': {'continent': ['Africa'], 'name': 'Togo'},
    'TH': {'continent': ['Asia'], 'name': 'Thailand'},
    'TJ': {'continent': ['Asia'], 'name': 'Tajikistan'},
    'TM': {'continent': ['Asia'], 'name': 'Turkmenistan'},
    'TN': {'continent': ['Africa'], 'name': 'Tunisia'},
    'TO': {'continent': ['Oceania'], 'name': 'Tonga'},
    'TR': {'continent': ['Asia', 'Europe'], 'name': 'Turkey'},
    'TT': {'continent': ['North America'],
           'name': 'Trinidad and Tobago'},
    'TV': {'continent': ['Oceania'], 'name': 'Tuvalu'},
    'TZ': {'continent': ['Africa'], 'name': 'Tanzania'},
    'UA': {'continent': ['Europe'], 'name': 'Ukraine'},
    'UG': {'continent': ['Africa'], 'name': 'Uganda'},
    'US': {'continent': ['North America'], 'name': 'United States'},
    'UY': {'continent': ['South America'], 'name': 'Uruguay'},
    'UZ': {'continent': ['Asia'], 'name': 'Uzbekistan'},
    'VA': {'continent': ['Europe'], 'name': 'Vatican City'},
    'VE': {'continent': ['South America'], 'name': 'Venezuela'},
    'VN': {'continent': ['Asia'], 'name': 'Vietnam'},
    'VU': {'continent': ['Oceania'], 'name': 'Vanuatu'},
    'YE': {'continent': ['Asia'], 'name': 'Yemen'},
    'YU': {'continent': ['Europe'], 'name': 'Yugoslavia'},
    'ZM': {'continent': ['Africa'], 'name': 'Zambia'},
    'ZW': {'continent': ['Africa'], 'name': 'Zimbabwe'},
    'DZ': {'continent': ['Africa'], 'name': 'Algeria'},
    'BA': {'continent': ['Europe'], 'name': 'Bosnia and Herzegovina'},
    'KH': {'continent': ['Asia'], 'name': 'Cambodia'},
    'CF': {'continent': ['Africa'],
           'name': 'Central African Republic'},
    'TD': {'continent': ['Africa'], 'name': 'Chad'},
    'KM': {'continent': ['Africa'], 'name': 'Comoros'},
    'HR': {'continent': ['Europe'], 'name': 'Croatia'},
    'TL': {'continent': ['Asia'], 'name': 'East Timor'},
    'SV': {'continent': ['North America'], 'name': 'El Salvador'},
    'GQ': {'continent': ['Africa'], 'name': 'Equatorial Guinea'},
    'GD': {'continent': ['North America'], 'name': 'Grenada'},
    'KZ': {'continent': ['Asia', 'Europe'], 'name': 'Kazakhstan'},
    'LA': {'continent': ['Asia'], 'name': 'Laos'},
    'FM': {'continent': ['Oceania'],
           'name': 'Federated States of Micronesia'},
    'MD': {'continent': ['Europe'], 'name': 'Moldova'},
    'MC': {'continent': ['Europe'], 'name': 'Monaco'},
    'ME': {'continent': ['Europe'], 'name': 'Montenegro'},
    'MA': {'continent': ['Africa'], 'name': 'Morocco'},
    'KN': {'continent': ['North America'],
           'name': 'Saint Kitts and Nevis'},
    'LC': {'continent': ['North America'], 'name': 'Saint Lucia'},
    'VC': {'continent': ['North America'],
           'name': 'Saint Vincent and the Grenadines'},
    'WS': {'continent': ['Oceania'], 'name': 'Samoa'},
    'RS': {'continent': ['Europe'], 'name': 'Serbia'},
    'ZA': {'continent': ['Africa'], 'name': 'South Africa'},
    'ES': {'continent': ['Europe'], 'name': 'Spain'},
    'LK': {'continent': ['Asia'], 'name': 'Sri Lanka'},
    'SZ': {'continent': ['Africa'], 'name': 'Swaziland'},
    'CH': {'continent': ['Europe'], 'name': 'Switzerland'},
    'AE': {'continent': ['Asia'], 'name': 'United Arab Emirates'},
    'GB': {'continent': ['Europe'], 'name': 'United Kingdom'},
}

CONTINENTS = ['Europe', 'Asia', 'North America', 'South America',
              'Oceania', 'Africa', 'Antarctica']

COUNTRY_CODE_SCHEMA = json.loads(pkg_resources.resource_string(
    'inspirehep', os.path.join('modules', 'records',
                               'jsonschemas', 'records',
                               'elements','country_code.json')
    ))
