#!/bin/bash
#
# This file is part of INSPIRE.
# Copyright (C) 2014-2017 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this license, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

find inspirehep -name "*.json" | while read -r file; do
  # python -m json.tool cannot be used here because in Python 2 it doesn't
  # handle in-place file substitution (which was added in Python 3).
  python -c "import json; \
    input = json.load(open('${file}', 'r')); \
    output = json.dumps(input, indent=4, sort_keys=True); \
    open('${file}', 'w').write(output.replace(', \n', ',\n') + '\n')"
done
