#!/bin/sh
set -e

# This file is part of INSPIRE.
# Copyright (C) 2016 CERN.
#
# INSPIRE is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# INSPIRE is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with INSPIRE. If not, see <http://www.gnu.org/licenses/>.
#
# In applying this licence, CERN does not waive the privileges and immunities
# granted to it by virtue of its status as an Intergovernmental Organization
# or submit itself to any jurisdiction.

if [ ! -d "${VIRTUAL_ENV}" ]; then
  >&2 echo "You must be in a virtual environment to use this script."
  exit 1
fi

if [ ! -x "$(command -v inspirehep)" ]; then
  >&2 echo "You must have the inspirehep command to use this script."
  exit 1
fi

if [ ! -x "$(command -v celery)" ]; then
  >&2 echo "You must have the celery command to use this script."
  exit 1
fi

# If we're not running in Docker also start celery.
if [ $(pwd) != "/code" ]; then
	CELERY_LOGLEVEL=$1
	if [ -z $1 ]; then
		CELERY_LOGLEVEL="ERROR"
	fi

	cleanup() {
		echo "----> Killing Celery Worker ${CELERY_PID}"
		kill "${CELERY_PID}"
	}

	CELERY_PIDFILE="${VIRTUAL_ENV}/worker.pid"
	if [ -f "${CELERY_PIDFILE}" ]; then
		echo "----> Purging all pending messages"
		celery purge -f -A inspirehep.celery --workdir="${VIRTUAL_ENV}"
	else
		celery worker -E -A inspirehep.celery --loglevel=${CELERY_LOGLEVEL} --workdir="${VIRTUAL_ENV}" --autoreload --pidfile="${CELERY_PIDFILE}" --purge &
		CELERY_PID=$!
		trap 'cleanup' 0 1 2 3 6
	fi
fi

inspirehep db drop --yes-i-know
inspirehep db create
inspirehep index destroy --force --yes-i-know
inspirehep index init

inspirehep migrator populate -f inspirehep/demosite/data/demo-records.xml.gz --wait=true

