name: Push master

on:
  push:
    branches: [master]
  release:
    types: [released]

defaults:
  run:
    shell: bash

jobs:
  test:
    uses: ./.github/workflows/backend-tests-on-docker.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: send event (release)
        if : ${{  github.event_name == 'release' }}
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.3.1
        with:
          repo: cern-sis/kubernetes-inspire
          event-type: release
          images: |
            inspirehep/next@${{ needs.test.outputs.tag }}
            inspirehep/next-assets@${{ needs.test.outputs.tag }}
            inspirehep/next-scrapyd@${{ needs.test.outputs.tag }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}

      - name: send event (update)
        if : ${{  github.event_name != 'release' }}
        uses: cern-sis/gh-workflows/.github/actions/kubernetes-project-new-images@v6.3.1
        with:
          repo: cern-sis/kubernetes-inspire
          event-type: update
          images: |
            inspirehep/next@${{ needs.test.outputs.tag }}
            inspirehep/next-assets@${{ needs.test.outputs.tag }}
            inspirehep/next-scrapyd@${{ needs.test.outputs.tag }}
          token: ${{ secrets.PAT_FIRE_EVENTS_ON_CERN_SIS_KUBERNETES }}
