name: Push development

on:
  push:
    branches: ['action-development-*']

jobs:
  test:
    uses: ./.github/workflows/backend-tests-on-docker.yml
    with:
      ref: ${{ github.event.pull_request.head.sha }}
    secrets: inherit

